export const MOCK_WARDROBE_ITEMS = [
  {
    id: 'e2e-item-top',
    imageUrl: 'https://picsum.photos/seed/e2e-top/400/400',
    mainCategory: 'TOP',
    subCategory: 'Button-Up Shirt',
    season: ['summer'],
    material: ['cotton'],
    description: 'White cotton button-up shirt.',
    colors: ['white'],
    tags: ['office'],
    searchDescription: 'Office commute white shirt.',
    occasions: ['office commute'],
    formality: 'smart-casual',
    silhouette: ['regular'],
    createdAt: '2026-08-31T00:00:00.000Z',
    updatedAt: '2026-08-31T00:00:00.000Z',
    clientProfileId: 'e2e-client',
  },
  {
    id: 'e2e-item-bottom',
    imageUrl: 'https://picsum.photos/seed/e2e-bottom/400/400',
    mainCategory: 'BOTTOM',
    subCategory: 'Wide-Leg Trousers',
    season: ['summer'],
    material: ['linen'],
    description: 'Cream wide-leg trousers.',
    colors: ['cream'],
    tags: ['casual'],
    searchDescription: 'Office commute wide-leg trousers.',
    occasions: ['office commute'],
    formality: 'smart-casual',
    silhouette: ['wide-leg'],
    createdAt: '2026-08-31T00:00:00.000Z',
    updatedAt: '2026-08-31T00:00:00.000Z',
    clientProfileId: 'e2e-client',
  },
];

export const MOCK_PROFILE = {
  profileData: {
    name: 'E2E Tester',
    height: '170',
    weight: '60',
    personal_style: '日常休闲',
    preferences: ['简约'],
    visual_profile_verified: false,
    style_keywords: ['minimal'],
    body_type: '',
    color_palette: [],
    face_shape: '',
    skin_tone: '',
    hair_style: '',
  },
};
